app:
  name: app
  group: app
  replicaCount: 1
  container:
    image: add-image-here
    imagePullPolicy: Always
    port: 8080
    config: [ ]
    env:
      - key: key
        value: value
  service:
    type: ClusterIP
    port: 8080
  