ingress:
  name: ingress-service
  replicaCount: 1
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            serviceName: serviceName
            servicePort: 8080
  tls:
    secretName: example-issuer-account-key
  